### ISSUE TITLE
Integration with Jekyll

### ISSUE THREAD

**Issue by formula1** [formula1/NodeOS-Blog#5]
This is more associated with allowing the person to specify Template and desitination folder when running the compile script

```
compiler = require("compiler");

compiler.compileHTML("/input/dir/path", "/template/path", "/output/dir/path",next)
compiler.compileJS(["modules",{path:"to/require", options:{exposes:"name"}}, "/output/dir/path",next)
```

The only thing that templates would need with jekyll is the [Front Matter](http://jekyllrb.com/docs/frontmatter/). Outside of that theres nothing more to worry about. A good example is [here](https://github.com/NodeOS/nodeos.github.io/blob/master/_layouts/blog.html). Now, I'm compiling it with ejs, however ejs can techniclaly output anything.

BTW, [piranna kicking ass left and right!](https://github.com/npm/npm/pull/5518)

**Comment by formula1** [comment]
Scratch that, I can have much better integration while avoiding ejs completely.

http://jekyllrb.com/docs/templates/#includes

**Comment by formula1** [comment]
https://github.com/formula1/nodeos.github.io

I'm not automating the integration, but for what its worth this is for a specific website.

**Comment by piranna** [comment]
> BTW, piranna kicking ass left and right!

First rule of open software: if you found some work that need to be done, it's your work ;-)

> https://github.com/formula1/nodeos.github.io
> 
> I'm not automating the integration, but for what its worth this is for a specific website.

We can integrate it directly on the NodeOS site code, but since GitHub allow to sirectly access to project pages on an organization, I think it's a better alternative...
